<?
$xml=new DOMDocument('1.0','windows-1251');
$xml_declar=$xml->createElement('DECLAR');
$xml->appendChild($xml_declar);
$xml_declar->setAttributeNS('http://www.w3.org/2000/xmlns/','xmlns:xsi','http://www.w3.org/2001/XMLSchema-instance');
$xml_declar->setAttributeNS('http://www.w3.org/2001/XMLSchema-instance','noNamespaceSchemaLocation',$file.'.xsd');
$xml_dh=$xml->createElement('DECLARHEAD');
$xml_declar->appendChild($xml_dh);
$xml_tin=SNode($xml,$xml_dh,'TIN',$tin);
$xml_cdoc=SNode($xml,$xml_dh,'C_DOC',substr($file,0,3));
$xml_cdocsub=SNode($xml,$xml_dh,'C_DOC_SUB',substr($file,3,3));
$xml_cdocver=SNode($xml,$xml_dh,'C_DOC_VER',(int)substr($file,6,2));
$xml_cdoctype=SNode($xml,$xml_dh,'C_DOC_TYPE',$doc_type);
$xml_cdoccnt=SNode($xml,$xml_dh,'C_DOC_CNT',$doc_cnt);
$xml_cdocreg=SNode($xml,$xml_dh,'C_REG',substr($taxCode,0,2));
$xml_cdocraj=SNode($xml,$xml_dh,'C_RAJ',(int)substr($taxCode,-2));
$xml_pm=SNode($xml,$xml_dh,'PERIOD_MONTH',$month);
$xml_pt=SNode($xml,$xml_dh,'PERIOD_TYPE',$period_type);
$xml_py=SNode($xml,$xml_dh,'PERIOD_YEAR',$year);
$xml_cstiorig=SNode($xml,$xml_dh,'C_STI_ORIG',$taxCode);
$xml_cdocstan=SNode($xml,$xml_dh,'C_DOC_STAN',$doc_stan);
$xml_linkdoc=SNode($xml,$xml_dh,'LINKED_DOCS');
$xml_dfill=SNode($xml,$xml_dh,'D_FILL',$date);
$xml_soft=SNode($xml,$xml_dh,'SOFTWARE',$software);
$xml_db=$xml->createElement('DECLARBODY');
$xml_declar->appendChild($xml_db);
?>
